//
//  GlobalStratagems.swift
//  Helldivers Companion
//
//  Created by James Poole on 24/02/2026.
//

var globalStratagems: [Stratagem] = [
    Stratagem(name: "Machine Gun", sequence: [.down, .left, .down, .up, .right], type: .admin, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199811/machine-gun_mayvjv.mp4"),
    Stratagem(name: "Airburst Rocket Launcher", sequence: [.down, .up, .up, .left, .right], type: .admin, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199781/airburst-rocket-launcher_zba4cf.mp4"),
    Stratagem(name: "Anti-Materiel Rifle", sequence: [.down, .left, .right, .up, .down], type: .admin, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199781/anti-materiel-rifle_qxi0dx.mp4"),
    Stratagem(name: "Stalwart", sequence: [.down, .left, .down, .up, .up, .left], type: .admin, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199838/stalwart_haa0p9.mp4"),
    Stratagem(name: "Expendable Anti-Tank", sequence: [.down, .down, .left, .up, .right], type: .admin, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199796/expendable-anti-tank_vyziwa.mp4"),
    Stratagem(name: "Recoilless Rifle", sequence: [.down, .left, .right, .right, .left], type: .admin, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199838/recoilless-rifle_qolpe1.mp4"),
    Stratagem(name: "Flamethrower", sequence: [.down, .left, .up, .down, .up], type: .admin, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199797/flamethrower_pwedpe.mp4"),
    Stratagem(name: "Autocannon", sequence: [.down, .left, .down, .up, .up, .right], type: .admin, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199782/autocannon_ircqzc.mp4"),
    Stratagem(name: "Railgun", sequence: [.down, .right, .down, .up, .left, .right], type: .admin, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199829/railgun_s3vkpc.mp4"),
    Stratagem(name: "Spear", sequence: [.down, .down, .up, .down, .down], type: .admin, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199837/spear_rsyzpf.mp4"),
    Stratagem(name: "Orbital Gatling Barrage", sequence: [.right, .down, .left, .up, .up], type: .orbital, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199819/orbital-gatling-barrage_vnvvkn.mp4"),
    Stratagem(name: "Orbital Airburst Strike", sequence: [.right, .right, .right], type: .orbital, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199819/orbital-airburst-strike_hqynoz.mp4"),
    Stratagem(name: "Orbital 120MM HE Barrage", sequence: [.right, .right, .down, .left, .right, .down], type: .orbital, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199811/orbital-120mm-he-barrage_psualf.mp4"),
    Stratagem(name: "Orbital 380MM HE Barrage", sequence: [.right, .down, .up, .up, .left, .down, .down], type: .orbital, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199811/orbital-380mm-he-barrage_fiftgw.mp4"),
    Stratagem(name: "Orbital Walking Barrage", sequence: [.right, .down, .right, .down, .right, .down], type: .orbital, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199830/orbital-walking-barrage_tbduw8.mp4"),
    Stratagem(name: "Orbital Laser", sequence: [.right, .down, .up, .right, .down], type: .orbital, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199819/orbital-laser_lcjewz.mp4"),
    Stratagem(name: "Orbital Railcannon Strike", sequence: [.right, .up, .down, .down, .right], type: .orbital, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199830/orbital-railcannon-strike_nxeirs.mp4"),
    Stratagem(name: "Eagle Strafing Run", sequence: [.up, .right, .right], type: .hangar, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199791/eagle-strafing-run_bluamq.mp4"),
    Stratagem(name: "Eagle Airstrike", sequence: [.up, .right, .down, .right], type: .hangar, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199791/eagle-airstrike_t51mo5.mp4"),
    Stratagem(name: "Eagle Cluster Bomb", sequence: [.up, .right, .down, .down, .right], type: .hangar, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199791/eagle-cluster-bomb_dotcej.mp4"),
    Stratagem(name: "Eagle Napalm Airstrike", sequence: [.up, .right, .down, .up], type: .hangar, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199791/eagle-napalm-airstrike_m9jrjs.mp4"),
    Stratagem(name: "Jump Pack", sequence: [.down, .up, .up, .down, .up], type: .hangar, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199804/jump-pack_h5a424.mp4"),
    Stratagem(name: "Eagle Smoke Strike", sequence: [.up, .right, .up, .down], type: .hangar, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199791/eagle-smoke-strike_n0hnrs.mp4"),
    Stratagem(name: "Eagle 110MM Rocket Pods", sequence: [.up, .right, .up, .left], type: .hangar, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199784/eagle-110mm-rocket-pods_ueooxq.mp4"),
    Stratagem(name: "Eagle 500KG Bomb", sequence: [.up, .right, .down, .down, .down], type: .hangar, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199791/eagle-500kg-bomb_snom6r.mp4"),
    Stratagem(name: "Orbital Precision Strike", sequence: [.right, .right, .up], type: .bridge, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199819/orbital-precision-strike_hqa22z.mp4"),
    Stratagem(name: "Orbital Gas Strike", sequence: [.right, .right, .down, .right], type: .bridge, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199819/orbital-gas-strike_eou2w6.mp4"),
    Stratagem(name: "Orbital EMS Strike", sequence: [.right, .right, .left, .down], type: .bridge, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199819/orbital-ems-strike_fefzss.mp4"),
    Stratagem(name: "Orbital Smoke Strike", sequence: [.right, .right, .down, .up], type: .bridge, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199830/orbital-smoke-strike_jffrd7.mp4"),
    Stratagem(name: "HMG Emplacement", sequence: [.down, .up, .left, .right, .right, .left], type: .bridge, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199804/hmg-emplacement_w1u00u.mp4"),
    Stratagem(name: "Shield Generator Relay", sequence: [.down, .down, .left, .right, .left, .right], type: .bridge, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199837/shield-generator-relay_uqp8ky.mp4"),
    Stratagem(name: "Tesla Tower", sequence: [.down, .up, .right, .up, .left, .right], type: .bridge, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199970/tesla-tower_nezgdq.mp4"),
    Stratagem(name: "Anti-Personnel Minefield", sequence: [.down, .left, .up, .right], type: .engineering, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199781/anti-personnel-minefield_vnwjiz.mp4"),
    Stratagem(name: "Supply Pack", sequence: [.down, .left, .down, .up, .up, .down], type: .engineering, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199839/supply-pack_wdm33j.mp4"),
    Stratagem(name: "Grenade Launcher", sequence: [.down, .left, .up, .left, .down], type: .engineering, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199797/grenade-launcher_xz48sg.mp4"),
    Stratagem(name: "Laser Cannon", sequence: [.down, .left, .down, .up, .left], type: .engineering, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199811/laser-cannon_hdo80e.mp4"),
    Stratagem(name: "Incendiary Mines", sequence: [.down, .left, .left, .down], type: .engineering, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199804/incendiary-mines_m1vwjw.mp4"),
    Stratagem(name: "Guard Dog Rover", sequence: [.down, .up, .left, .up, .right, .right], type: .engineering, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199804/guard-dog-rover_qadjo4.mp4"),
    Stratagem(name: "Ballistic Shield Backpack", sequence: [.down, .left, .down, .down, .up, .left], type: .engineering, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199784/ballistic-shield-backpack_tp6mc1.mp4"),
    Stratagem(name: "Arc Thrower", sequence: [.down, .right, .down, .up, .left, .left], type: .engineering, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199781/arc-thrower_bhmsyb.mp4"),
    Stratagem(name: "Shield Generator Pack", sequence: [.down, .up, .left, .right, .left, .right], type: .engineering, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199837/shield-generator-pack_fz0mp8.mp4"),
    Stratagem(name: "Machine Gun Sentry", sequence: [.down, .up, .right, .right, .up], type: .workshop, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199811/machine-gun-sentry_ude1jr.mp4"),
    Stratagem(name: "Gatling Sentry", sequence: [.down, .up, .right, .left], type: .workshop, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199797/gatling-sentry_j1dksf.mp4"),
    Stratagem(name: "Mortar Sentry", sequence: [.down, .up, .right, .right, .down], type: .workshop, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199811/mortar-sentry_j8p4xp.mp4"),
    Stratagem(name: "Guard Dog", sequence: [.down, .up, .left, .up, .right, .down], type: .workshop, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199804/guard-dog_nxqhnj.mp4"),
    Stratagem(name: "Autocannon Sentry", sequence: [.down, .up, .right, .up, .left, .up], type: .workshop, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199782/autocannon-sentry_mqci5o.mp4"),
    Stratagem(name: "Rocket Sentry", sequence: [.down, .up, .right, .right, .left], type: .workshop, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199837/rocket-sentry_dwzvlz.mp4"),
    Stratagem(name: "EMS Mortar Sentry", sequence: [.down, .up, .right, .down, .right], type: .workshop, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199797/ems-mortar-sentry_ipu2rr.mp4"),
    Stratagem(name: "Reinforce", sequence: [.up, .down, .right, .left, .up], type: .mission),
    Stratagem(name: "SOS Beacon", sequence: [.up, .down, .right, .up], type: .mission),
    Stratagem(name: "Super Earth Flag", sequence: [.down, .up, .down, .up], type: .mission),
    Stratagem(name: "Upload Data", sequence: [.left, .right, .up, .up, .up], type: .mission),
    Stratagem(name: "Hellbomb", sequence: [.down, .up, .left, .down, .up, .right, .down, .up], type: .mission),
    Stratagem(name: "Patriot Exosuit", sequence: [.left, .down, .right, .up, .left, .down, .down], type: .workshop, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199830/patriot-exosuit_khycyw.mp4"),
    Stratagem(name: "Emancipator Exosuit", sequence: [.left, .down, .right, .up, .left, .down, .up], type: .workshop, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199796/emancipator-exosuit_t6acx6.mp4"),
    Stratagem(name: "Quasar Cannon", sequence: [.down, .down, .up, .left, .right], type: .engineering, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199830/quasar-cannon_sdgkmx.mp4"),
    Stratagem(name: "Heavy Machine Gun", sequence: [.down, .left, .up, .down, .down], type: .admin, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1721199804/heavy-machine-gun_mqll1v.mp4"),
    Stratagem(name: "Resupply", sequence: [.down, .down, .up, .right], type: .mission),
    Stratagem(name: "Prospecting Drill", sequence: [.down, .down, .left, .right, .down, .down], type: .mission),
    Stratagem(name: "Seismic Probe", sequence: [.up, .up, .left, .right, .down, .down], type: .mission),
    Stratagem(name: "SEAF Artillery", sequence: [.right, .up, .up, .down], type: .mission),
    Stratagem(name: "Orbital Illumination Flare", sequence: [.right, .right, .left, .left], type: .mission),
    Stratagem(name: "Guard Dog Breath", sequence: [.down, .up, .left, .right, .up], type: .workshop, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1734822317/guard-dog-dog-breath-2.mp4"),
    Stratagem(name: "Tectonic Drill", sequence: [.up, .down, .up, .down, .up, .down], type: .mission),
    Stratagem(name: "Dark Fluid Vessel", sequence: [.up, .left, .right, .down, .up, .up], type: .mission),
    Stratagem(name: "Hive Breaker Drill", sequence: [.left, .up, .down, .right, .down, .down], type: .mission),
    Stratagem(name: "Orbital Napalm Barrage", sequence: [.right, .right, .down, .left, .right, .up], type: .orbital, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1734822296/orbital-napalm-barrage-2.mp4"),
    Stratagem(name: "Directional Shield", sequence: [.down, .up, .left, .right, .up, .up], type: .engineering, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1734822347/directional-shield-2.mp4"),
    Stratagem(name: "Anti-Tank Emplacement", sequence: [.down, .up, .left, .right, .right, .right], type: .workshop, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1734822398/anti-tank-emplacement-2.mp4"),
    Stratagem(name: "Flame Sentry", sequence: [.down, .up, .right, .down, .up, .up], type: .workshop, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1734822364/flame-sentry-2.mp4"),
    Stratagem(name: "Sterilizer", sequence: [.down, .left, .up, .down, .left], type: .admin, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1734822306/steriliser-2.mp4"),
    Stratagem(name: "Commando", sequence: [.down, .left, .up, .down, .right], type: .admin, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1734822285/commando-2.mp4"),
    Stratagem(name: "W.A.S.P. Launcher", sequence: [.down, .down, .up, .down, .right], type: .engineering, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1735089553/wasp-launcher-2.mp4"),
    Stratagem(name: "Fast Recon Vehicle", sequence: [.left, .down, .right, .down, .right, .down, .up], type: .hangar),
    Stratagem(name: "Anti-Tank Mines", sequence: [.down, .left, .up, .up], type: .engineering, videoUrl: "https://res.cloudinary.com/dxtkcvynb/video/upload/v1735089844/anti-tank-mines-2.mp4"),
    Stratagem(name: "Gas Mines", sequence: [.down, .left, .left, .right], type: .engineering)
]
