name: SwiftLint
on:
  pull_request:
    paths:
      - '**/*.swift'

jobs:
  swiftlint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run SwiftLint
        run: swiftlint --reporter github-actions-logging --strict
